name: Go
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: ["tip"]
    steps:
    - name: Set up Go ${{ matrix.go }}
      if: matrix.go != 'tip'
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Set up Go ${{ matrix.go }}
      if: matrix.go == 'tip'
      run: |
        export GOROOT_BOOTSTRAP=`go env GOROOT`
        export GOROOT=$HOME/gotip
        mkdir $HOME/gotip
        cd $HOME/gotip
        curl -s 'https://go.googlesource.com/go/+/refs/heads/master?format=JSON' | awk '/"commit"/{print substr($2,2,40);exit}' >HEAD
        awk '{printf("gotip-%s",substr($0,0,7))}' <HEAD >VERSION
        curl -s -o go.tar.gz https://go.googlesource.com/go/+archive/`cat HEAD`.tar.gz
        tar xfz go.tar.gz
        cd src
        bash make.bash
        echo "GOROOT=$GOROOT" >> $GITHUB_ENV
        echo "$GOROOT/bin" >> $GITHUB_PATH

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Verify go mod
      run: make go-mod-verify

    - name: Lint
      run: make lint

    - name: Test
      run: make test
