name: Go
on: [pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.21"]
    steps:
    - uses: actions/checkout@v3
  
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Verify go mod
      run: make go-mod-verify

    - name: Lint
      run: make lint
      continue-on-error: true

    - name: Test
      run: make test
