name: Go
on: [push, pull_request]
jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.14", "1.15"]
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Verify go mod
      run: make go-mod-verify
    - name: Lint
      run: make lint
    - name: Test
      run: make test
